//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartApartmentDataTestDataModule.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class guild_members
    {
        public int pk_id { get; set; }
        public Nullable<int> fk_player { get; set; }
        public Nullable<int> fk_guild { get; set; }
    
        public virtual player player { get; set; }
        public virtual guild guild { get; set; }
    }
}
