//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartApartmentDataTestDataModule.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public player()
        {
            this.guild_members = new HashSet<guild_members>();
        }
    
        public int pk_id { get; set; }
        public string name { get; set; }
        public string realm { get; set; }
        public string region { get; set; }
        public int fk_class { get; set; }
        public int fk_faction { get; set; }
        public int fk_race { get; set; }
        public Nullable<int> fk_user { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual faction faction { get; set; }
        public virtual race race { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<guild_members> guild_members { get; set; }
        public virtual user user { get; set; }
    }
}
